Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output"
  device: "gpu"
  save_interval: 20
  eval_during_train: True
  eval_interval: 20
  epochs: 400
  print_batch_step: 10
  use_visualdl: True
  use_ema: True
  ema_decay: 0.99996

Arch:
  name: "DistillationModel"
  class_num: 1000
  models:
    - Teacher:
        name: RegNetY_160
    - Student:
        name: XCiT_nano_12_p8
  pretrained_list: 
    - "regnety_160"
    - null
  freeze_params_list:
    - True
    - False
  infer_model_name: "Student"
  save_model_names: 

Loss:
  Train:
    - DistillationDMLLoss:
        weight: 0.5
        act: "softmax"
        model_name_pairs:
          - ["Student", "Teacher"]
    - DistillationGTCELoss:
        weight: 0.5
        model_names: ["Student"]
  Eval:
    - DistillationGTCELoss:
        weight: 1.0
        model_names: ["Student"]


Optimizer:
  name: AdamW
  weight_decay: 0.05
  lr: 
    name: Cosine
    learning_rate: 0.0005
    warmup_start_lr: 0.000001
    warmup_epoch: 5
    eta_min: 0.00001

DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: "data/ILSVRC2012/"
      cls_label_path: "data/ILSVRC2012/train_list.txt"
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
            backend: "pil"
            interpolation: "bicubic"
        - RandFlipImage:
            flip_code: 1
        - TimmAutoAugment:
            config_str: "rand-m9-mstd0.5-inc1"
            img_size: 224
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - RandomErasing:
            EPSILON: 0.25
            mode: "pixel"
            attempt: 1
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: False
      shuffle: True
    loader:
      num_workers: 6
      use_shared_memory: False
  Eval:
    dataset:
      name: ImageNetDataset
      image_root: "data/ILSVRC2012/"
      cls_label_path: "data/ILSVRC2012/val_list.txt"
      transform_ops: 
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 224
            interpolation: "bicubic"
            backend: "pil"
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 96
      drop_last: False
      shuffle: False
    loader:
      num_workers: 6
      use_shared_memory: False


Metric:
  Train: 
    - DistillationTopkAcc:
        model_key: "Student"
        topk: [1, 5]
  Eval:
    - DistillationTopkAcc:
        model_key: "Student"
        topk: [1, 5]